<a href="https://colab.research.google.com/github/yusroh/Numpy-exercises-/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.21.5'

# New Section

In [ ]:
import numpy as np 
arr = np.arange(16).reshape(4,4)
print(arr)
newarr = arr.reshape(2,4,2)
print(newarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [ ]:
import numpy as np
arr =np.ones((5,5,5)).astype(int) + 0
print(arr)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
from numpy.core.fromnumeric import searchsorted
arr = np.array([5,7,1,4,6,9])
x = np.searchsorted(arr, [4])
print(x)

[0]


In [ ]:
import numpy as np

arr = np.array([[12., 12.51], [2.34, 7.98], [25.23, 36.5]])
print(arr)
int_array = arr.astype(int)
print(int_array)

[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
[[12 12]
 [ 2  7]
 [25 36]]
